
package frc.robot;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj MinMovementShoot = new ChoreoTraj(
	    "MinMovementShoot",
	    OptionalInt.empty(),
	    0.65901,
	    new Pose2d(3.607, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(2.032, 4.035, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ShootAndClimb = new ChoreoTraj(
	    "ShootAndClimb",
	    OptionalInt.empty(),
	    1.17681,
	    new Pose2d(3.607, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(1.586, 4.111, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj ShootAndClimb$0 = new ChoreoTraj(
	    "ShootAndClimb",
	    OptionalInt.of(0),
	    0.58552,
	    new Pose2d(3.607, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(2.374, 4.014, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ShootAndClimb$1 = new ChoreoTraj(
	    "ShootAndClimb",
	    OptionalInt.of(1),
	    0.5912899999999999,
	    new Pose2d(2.374, 4.014, Rotation2d.fromRadians(0)),
	    new Pose2d(1.586, 4.111, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj ShootCollectClimb = new ChoreoTraj(
	    "ShootCollectClimb",
	    OptionalInt.empty(),
	    5.7208,
	    new Pose2d(3.607, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(1.657, 3.955, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj ShootCollectClimb$0 = new ChoreoTraj(
	    "ShootCollectClimb",
	    OptionalInt.of(0),
	    0.65506,
	    new Pose2d(3.607, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(2.032, 4.035, Rotation2d.fromRadians(-0.017))
	);
	public static final ChoreoTraj ShootCollectClimb$1 = new ChoreoTraj(
	    "ShootCollectClimb",
	    OptionalInt.of(1),
	    5.06574,
	    new Pose2d(2.032, 4.035, Rotation2d.fromRadians(-0.017)),
	    new Pose2d(1.657, 3.955, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj ShootCollectPass = new ChoreoTraj(
	    "ShootCollectPass",
	    OptionalInt.empty(),
	    5.93692,
	    new Pose2d(3.607, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(5.71, 5.843, Rotation2d.fromRadians(-3.131))
	);
	public static final ChoreoTraj ShootCollectPass$0 = new ChoreoTraj(
	    "ShootCollectPass",
	    OptionalInt.of(0),
	    0.65901,
	    new Pose2d(3.607, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(2.032, 4.035, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ShootCollectPass$1 = new ChoreoTraj(
	    "ShootCollectPass",
	    OptionalInt.of(1),
	    3.28178,
	    new Pose2d(2.032, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(5.647, 2.534, Rotation2d.fromRadians(3.132))
	);
	public static final ChoreoTraj ShootCollectPass$2 = new ChoreoTraj(
	    "ShootCollectPass",
	    OptionalInt.of(2),
	    1.99613,
	    new Pose2d(5.647, 2.534, Rotation2d.fromRadians(3.132)),
	    new Pose2d(5.71, 5.843, Rotation2d.fromRadians(-3.131))
	);
	public static final ChoreoTraj ShootCollectShoot = new ChoreoTraj(
	    "ShootCollectShoot",
	    OptionalInt.empty(),
	    5.05192,
	    new Pose2d(3.607, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(2.809, 5.055, Rotation2d.fromRadians(-0.524))
	);
	public static final ChoreoTraj ShootCollectShoot$0 = new ChoreoTraj(
	    "ShootCollectShoot",
	    OptionalInt.of(0),
	    0.65901,
	    new Pose2d(3.607, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(2.032, 4.035, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ShootCollectShoot$1 = new ChoreoTraj(
	    "ShootCollectShoot",
	    OptionalInt.of(1),
	    4.39291,
	    new Pose2d(2.032, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(2.809, 5.055, Rotation2d.fromRadians(-0.524))
	);
	public static final ChoreoTraj ShootDepotClimb = new ChoreoTraj(
	    "ShootDepotClimb",
	    OptionalInt.empty(),
	    2.46106,
	    new Pose2d(3.607, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(1.624, 3.893, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj ShootDepotClimb$0 = new ChoreoTraj(
	    "ShootDepotClimb",
	    OptionalInt.of(0),
	    0.46657,
	    new Pose2d(3.607, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(2.032, 4.035, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ShootDepotClimb$1 = new ChoreoTraj(
	    "ShootDepotClimb",
	    OptionalInt.of(1),
	    1.9944899999999999,
	    new Pose2d(2.032, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(1.624, 3.893, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj ShootDepotShoot = new ChoreoTraj(
	    "ShootDepotShoot",
	    OptionalInt.empty(),
	    2.53567,
	    new Pose2d(3.607, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(1.75, 4.035, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ShootDepotShoot$0 = new ChoreoTraj(
	    "ShootDepotShoot",
	    OptionalInt.of(0),
	    0.46657,
	    new Pose2d(3.607, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(2.032, 4.035, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj ShootDepotShoot$1 = new ChoreoTraj(
	    "ShootDepotShoot",
	    OptionalInt.of(1),
	    2.0691,
	    new Pose2d(2.032, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(1.75, 4.035, Rotation2d.fromRadians(0))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("MinMovementShoot", MinMovementShoot),
		Map.entry("ShootAndClimb", ShootAndClimb),
		Map.entry("ShootAndClimb$0", ShootAndClimb$0),
		Map.entry("ShootAndClimb$1", ShootAndClimb$1),
		Map.entry("ShootCollectClimb", ShootCollectClimb),
		Map.entry("ShootCollectClimb$0", ShootCollectClimb$0),
		Map.entry("ShootCollectClimb$1", ShootCollectClimb$1),
		Map.entry("ShootCollectPass", ShootCollectPass),
		Map.entry("ShootCollectPass$0", ShootCollectPass$0),
		Map.entry("ShootCollectPass$1", ShootCollectPass$1),
		Map.entry("ShootCollectPass$2", ShootCollectPass$2),
		Map.entry("ShootCollectShoot", ShootCollectShoot),
		Map.entry("ShootCollectShoot$0", ShootCollectShoot$0),
		Map.entry("ShootCollectShoot$1", ShootCollectShoot$1),
		Map.entry("ShootDepotClimb", ShootDepotClimb),
		Map.entry("ShootDepotClimb$0", ShootDepotClimb$0),
		Map.entry("ShootDepotClimb$1", ShootDepotClimb$1),
		Map.entry("ShootDepotShoot", ShootDepotShoot),
		Map.entry("ShootDepotShoot$0", ShootDepotShoot$0),
		Map.entry("ShootDepotShoot$1", ShootDepotShoot$1)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
